### ISSUE TITLE
can't figure out how to create a short code containing custom field

### ISSUE THREAD

**Issue by mannermax** [TypeRocket/typerocket#102]
I can't figure how to create a short code containing custom field
function job_title($atts, $content = null ) {
	echo $form->text('Job Title');
}
add_shortcode('sc_job_title', 'job_title');

tnks in advance
max

P.S.
It is possible that this example on github doesn't work
// Register Post Type
$person = tr_post_type('Person');

// Chain Methods with Eloquence
$person->setIcon('users')
     ->setTitlePlaceholder( 'Enter full name here' )
     ->setArchivePostsPerPage(-1);
     ->setTitleForm( function() {
         $form = tr_form();
         echo $form->image('Photo');
         echo $editor->text('Company');
         echo $editor->textarea('About Person');
     });

// Add Sortable Columns to Admin Index View
$person->addColumn('company', true);

// REST API
$person->setRest('person');

**Comment by kevindees** [comment]
Hey @mannermax 

Unfortunately using a shortcode to add form fields will not work because you need to have access to the main `$form` object. this is more of a limitation in shortcodes than in TypeRocket. This is not to say it can not be done but it would require some advanced PHP/WP knowledge.

What error are you getting with the example? Did you flush to permalinks?

Thanks,
Kevin

**Comment by mannermax** [comment]
thanks kevindees... Yep always forget flush permalinks
