### ISSUE TITLE
How to add repeaters meta fields on specific page only?

### ISSUE THREAD

**Issue by dipak24** [TypeRocket/typerocket#122]
Hello typerocket team,
Thanks for the awesome framework. I am using typerocket framework on my project I want to add repeatable fields on my specific page only ( Our Team ). I don't find any example for the specific page only. 

code #
$boxPosts= tr_meta_box('Social Media');
$boxPosts->addScreen('post', 'our-team');
$boxPosts->setCallback(function(){
    $form = tr_form();
    echo $form->image('Banner Image');
    echo $form->text('Subheading');
});

If i put only post it will be apply for all page .... i don't wan show this fields for other page

**Comment by kevindees** [comment]
Hey @dipak24 

Thanks for the kind words.

TypeRocket does not support conditional meta boxes. The builder field was designed to address situations like yours by allowing you to construct pages with components instead of toggling a number of meta boxes.

If you need to toggle a meta box based on page slug you will need to add a little of your own jQuery magic to pull it off yourself.

Thanks,
Kevin
