### ISSUE TITLE
About to start 2x projects with TypeRocket: Root or Theme install?

### ISSUE THREAD

**Issue by TheNicholasNick** [TypeRocket/typerocket#133]
Theme pros are I can send an updated theme and boom, prod site is updated, no worries.
As a theme, all the functionality I'm building is portable, have wp, got themes, click install theme, get functionality. 

Root pros are that I have full control over everything.
Not so portable, ftp files to server, update config items for that host, good to go.

I'm building apps, not information display pages.
These apps have extensive security considerations, basically, Role Based Access Control.

I have a feeling root install is the way to go.
This way I get access to who is using the site up front in the request and can make choices quickly and efficiently as to continue or redirect to where needed.

Now that I'm fairly sure I'm going the root way, how are updates handled?
Are there hooks to somewhere that signal database migrations/schema updates should happen or is it roll your own territory?

**Hopefully you guys can give a few pointers here, thanks.**

```markdown
# Why I picked TypeRocket

  * PHP is everywhere, hosting PHP is way simpler than anything else.  
  * Wordpress is everywhere and familiar and gets a lot of focus 
    security wise.  
  * Wordpress Admin UI is pretty enough.  
  * TypeRocket just uses the Wordpress UI and slots into that nicely.  
  * On the frontend I can access all the new MVC stuff that TypeRocket
    adds with ease.  
  * MVC for these two apps I'm building _(clone of wpschoolpress except the
    way I need it to work & a CRM system built specifically for a small
    business)_
  * Sure RubyOnRails probably could get me the same results, however, I'd
    need to spend **a lot of time** figuring out the HTML/CSS/JS for the UI.
    No thanks, I just want to write the business parts and have forms and
    datatables just magically appear.
    * Plus running and deploying RubyOnRails is not exactly straightforward,
      these apps need to be 99% hands off, set and forget. If there is an issue
      with Wordpress, it won't be many things, is the database contactable? is
      the webserver working? - that's pretty much it...

So that is a quick overview of how I came to choose TypeRocket. I wish this
existed 8yrs ago, would have made things a lot simpler. Sure my RoR solutions
worked, but again, starting with Wordpress gets you pretty far and saves
having to do a bunch of reptive tasks.
```

**Comment by kevindees** [comment]
Hey @SoreGums 

I hate I have not been able to respond until now. 

You are correct in thinking a root install is the way-to-go for a web app type scenario. The main idea you will care about is migrations. I have not documented migrations at this point because it is can get a bit complicated based on how you handle deploys and it would take quite a bit to cover each type of setup.

If you need something robust it might be worth finding a `composer` package that can handle what you are looking for.

#### Migrations in TypeRocket
 
To get started you need to configure the TypeRocket console to your WordPress install. You can read about this in the [Typerocket Docs for the Galaxy CLI](https://typerocket.com/docs/v3/galaxy-cli/#section-wp-commands).

Once you have the Galaxy CLI configured to WP you will see a few new commands. There are two you should care about: `make:migration` and `migrate`.

<img width="711" alt="screen shot 2018-09-25 at 8 45 28 am" src="https://user-images.githubusercontent.com/348368/46015189-9b249880-c09f-11e8-98db-e1fe253696aa.png">

##### Making a Migration

To make a migration run the command `make:migration`. For example, here I create a migration name `add_my_tables`.

```
php galaxy make:migration add_my_tables
```

Now, in my project, I have a new section called SQL.

<img width="327" alt="screen shot 2018-09-25 at 8 48 56 am" src="https://user-images.githubusercontent.com/348368/46015296-f35b9a80-c09f-11e8-95f5-3e7152561cfe.png">

Next, I need to add my migration SQL under the `>>> Up >>>` section (`>>> Down >>>` is used if you roll back a change) in the migration file. Also, each SQL statement needs to go on a new line and the line before must end with a semicolon `;`. If you need access to the WP DB prefix the migration will replace `{!!prefix!!}` with yours (default prefix is `wp_`). 

Here is an example of a migration that has not been run before:

```
-- Run At:
-- Description:
-- >>> Up >>>
CREATE TABLE `{!!prefix!!}my_custom_table` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `infor` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `{!!prefix!!}my_custom_table_2` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `infor` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- >>> Down >>>
DROP TABLE `{!!prefix!!}my_custom_table`;
DROP TABLE `{!!prefix!!}my_custom_table_2`;
```

To run the migration use the command `php galaxy migrate up`. Here is the output from that command:

<img width="465" alt="screen shot 2018-09-25 at 9 00 09 am" src="https://user-images.githubusercontent.com/348368/46015892-6c0f2680-c0a1-11e8-9cb4-2d51a4a09afb.png">

You can undo this migration by running `php galaxy migrate down`. Here is the output for that:

<img width="439" alt="screen shot 2018-09-25 at 9 01 26 am" src="https://user-images.githubusercontent.com/348368/46015975-98c33e00-c0a1-11e8-8360-8d348100c408.png">

If you only want to run a specific number of migrations using the commands you can add the number you want to run to the end of the command.

```
php galaxy migrate up 3
```

```
php galaxy migrate down 1
```


I hope this helps you get up and running. If you need a good server provision system I recommend using [Laravel Forge](https://forge.laravel.com/). That service makes it really easy to automatically run migrations when you deploy your code.

I hope this helps you out in your application development process.

Thanks,
Kevin
