### ISSUE TITLE
My Custom Post Type Controller and Model do not get executed when saving in admin

### ISSUE THREAD

**Issue by nebulousGirl** [TypeRocket/typerocket#155]
The generic model `App\Models\Post` gets called instead of the custom post type model I made. 

Is there an extra step to make it work?

**Comment by galingong** [comment]
All posts use the `Post` model by default. If you want to use custom models and controllers, you have to create a custom resource with `tr_resource_pages()` instead of a custom post type (custom post types are saved in `wp_posts` table, no matter what type, while a custom resource will use it's own table that you have to create yourself). Read the docs for further info: [https://typerocket.com/docs/v3/custom-resources/](url)

**Comment by nebulousGirl** [comment]
I understand that part. I want to use `wp_posts` table, but I need to save the meta data in a custom table instead of the postmeta table because I will have to do some advanced filtering and searches.

I would have thought that if I created [a model for my custom post type](https://typerocket.com/docs/v3/models/#section-model-class-template-code-post-model), that model would be used to save its posts. I had also assumed that if I created a [PostController for my custom post type,](https://typerocket.com/docs/v3/controllers/#section-post-controller) it would have been used when editing its posts in the admin panel.

**Comment by nebulousGirl** [comment]
Turns out I was not using the expected class names. While browsing the code for the core (which btw is really clean, I feel at home), I found the [PostsResponder ](https://github.com/TypeRocket/core/blob/master/src/Http/Responders/PostsResponder.php) class which camelizes the post type to find the model and the controller: 
```php
$type       = get_post_type( $id );
$resource   = Registry::getPostTypeResource( $type );
$prefix     = Str::camelize( $resource[0] );
$controller = "\\" . TR_APP_NAMESPACE . "\\Controllers\\{$prefix}Controller";
```

I wonder if there is a way to use other naming convention. I was naming my post type model EventPost and my post type controller EventPostController because I am using the Event name for my custom meta table.

**Comment by eric-michel** [comment]
@nebulousGirl Hope you don't mind me hijacking this to ask a quick question.

If I understand correctly, you're creating a table with a one-to-one relationship to your post type records so that you can save post metadata into individual database fields that are indexable. I'm doing similar, but creating a one-to-many relationship between my post type and the related table.

How are you handling deleting from the related table when the post is deleted? I can see that overriding theTypeRocket Model delete method doesn't work (which makes sense as WordPress is what's doing the deleting if you use the standard admin interface). Are you just using the before_delete_post action and going from there based on the post type?

I just want to make sure I'm not missing something simpler within TypeRocket that would handle this.

**Comment by nebulousGirl** [comment]
Great question! I had not thought about this from the code perspective.I have set a foreign key that cascades on delete in my database.On Jan 11, 2019 15:39, Eric Michel <notifications@github.com> wrote:@nebulousGirl Hope you don't mind me hijacking this to ask a quick question.
If I understand correctly, you're creating a table with a one-to-one relationship to your post type records so that you can save metadata there that's indexable. I'm doing similar, but creating a one-to-many relationship between my post type and the related table.
How are you handling deleting from the related table when the post is deleted? I can see that overriding theTypeRocket Model delete method doesn't work (which makes sense as WordPress is what's doing the deleting if you use the standard admin interface). Are you just using the before_delete_post action and going from there based on the post type?
I just want to make sure I'm not missing something simpler within TypeRocket that would handle this.

**Comment by eric-michel** [comment]
@nebulousGirl of course! I always overlook the easy solution. I'm so focused on overriding methods to get all the creating and updating right, I didn't just think about a cascade delete. Thanks for saving me a lot of work!
