### ISSUE TITLE
Typerocket Must-Use plugins

### ISSUE THREAD

**Issue by jerrebm** [TypeRocket/typerocket#179]
In a rooted typerocket instance, is it possible to add MU-plugins, so as to force Wordpress to use specifc plugins?

I'd prefer that over putting the plugins inside Wordpress' `mu-plugins` directory for security reasons, in the same way that we can keep theme files outside of the Wordpress directory.

**Comment by jerrebm** [comment]
For now, I did the following:

In the `wordpress/wp-content/mu-plugins` dir I added the following `typerocket-mu.php` file:

```php
<?php
/*
Plugin Name: TypeRocket Must-Use plugins
Description: Force Wordpress to load plugins from the mu-plugins dir
Author: TypeRocket
Version: 1.0.0
Author URI: http://typerocket.com
*/
if( defined('TR_PATH') ) {
    $dirs = glob(TR_PATH . '/plugins/mu-plugins/*' , GLOB_ONLYDIR);

    foreach($dirs as $dir) {
        if(file_exists($dir . DIRECTORY_SEPARATOR . basename($dir) . ".php")) {
            require($dir . DIRECTORY_SEPARATOR . basename($dir) . ".php");
        }
    }
}
```

Now any plugin placed in the `typerocket/plugins/mu-plugins` dir are automatically loaded, provided that the plugin's directory name and filename match.

**Comment by kevindees** [comment]
@egyptik 

The reason I have not made plugins work like themes is because plugins are much harder to move outside of public view when there are CSS and JS files included in the plugin. PHP only plugins are pretty easy to have added that way but most are not PHP only.

I do not plan to add that feature at this point but your modification to the system might be helpful to anyone who needs that functionality.

Thanks,
Kevin
