### ISSUE TITLE
Title Tag dont change

### ISSUE THREAD

**Issue by LuenCC** [TypeRocket/typerocket#20]
Hi when i use a "title Seo" dont change in the page.

In wordpress documentation said that 
        add_filter( 'wp_title', [$this, 'title'], 1, 3 ); 
"wp_title" is deprecated

If i change : now its working. In this file ->  typerocket\plugins\seo\init.php
add_filter( 'pre_get_document_title', [$this, 'title'], 9999999999, 3 );

**Comment by kevindees** [comment]
Hey @Luiscc2890,

Thanks for letting me know about the issue. I'm super glad you let me know.  I just submitted a patch to that file to fix the problem. I ended up going with `document_title_parts` since it gets called later than `pre_get_document_title` so that you can have more control over the output of the title.

You can see the commit here: https://github.com/TypeRocket/typerocket/commit/4b22b0cbf82a0c33e3fca29df848ffa7babcfb4e

Thanks again,
Kevin
