### ISSUE TITLE
Model doesn't save value in term meta

### ISSUE THREAD

**Issue by ascaroit** [TypeRocket/typerocket#207]
Im trying to add a custom field to woocommerce “product_cat” term.
I made a Model from Galaxy CLI, this is what's generated in typerocket/app/models/Product_cat.php

```
namespace App\Models;

use \TypeRocket\Models\WPTerm;

class Product_cat extends WPTerm
{
    protected $taxonomy = 'product_cat';
}

```

In  functions.php

```
    $prodCat = tr_taxonomy(‘product_cat’);

    $prodCat->setMainForm(function() {
        $form = tr_form();
        echo $form->text(‘Test’);
    });  

```
but this delete Products category from menu.
I see the text field in term page admin but
doesn't save any value.

**Comment by kevindees** [comment]
@ascaroit 

What plugins do you have installed on your WordPress site?

**Comment by ascaroit** [comment]
Query Monitor |   | by John Blackbourn – 3.3.6
-- | -- | --
Classic Editor |   | by Contributori WordPress – 1.4
Minimal Coming Soon & Maintenance Mode |   | by WebFactory – 1.2
Really Simple SSL |   | by Rogier Lankhorst, Mark Wolters – 3.1.5
WooCommerce |   | by Automattic – 3.6.3 – 3.6.4 è disponibile
Yoast SEO |   | by Team Yoast – 11.4 – Non testato con la versione attiva di WooCommerce
WP All Import Pro |   | by Soflyy – 4.5.5
WP All Import - WooCommerce Add-On Pro |   | by Soflyy – 3.0.6 – Non testato con la versione attiva di WooCommerce
YITH WooCommerce Waiting List |   | by YITH – 1.3.8

**Comment by kevindees** [comment]
Hey @ascaroit 

I'm still working on this one. I have not forgotten you.

**Comment by kevindees** [comment]
Hey @ascaroit 

I was able to get this fixed.  It looks like the current way of editing existing taxonomies was correct for built-in types only. If you pull the master branch of core you can now do the following to edit a taxonomy created by another plugin like WooCommerce.

```php
add_action('init', function() {
    $prodCat = tr_taxonomy('product_cat');

    $prodCat->setMainForm(function() {
        $form = tr_form();
        echo $form->text('Test');
    });

    // NEW call register 
    $prodCat->register();
});
```

The issue was that the WooCommerce post types and taxonomies are registered after TypeRocket ran and so TypeRocket could not find them in the system. Because they were not found no overriding happened. I was able to get a fix for this issue by requiring the override process to include using the `init` hook and calling `register()` manually.

**Comment by kevindees** [comment]
https://typerocket.com/docs/v4/taxonomies/#section-modify-existing-taxonomy
