### ISSUE TITLE
Shortcodes for a form

### ISSUE THREAD

**Issue by jamminjames** [TypeRocket/typerocket#223]
I'm using a plugin (WP Online Contract) that uses typerocket, and I was wondering if you could help me, as they are being no help at all. The plugin creates a form, and you place shortcodes in the form fields, which then are inserted in a contract that is presented to the customer. The shortcodes are supposed to show what was filled out in the fields that the shortcodes represent. However, the info is not being displayed. (See [test contract here](https://www.acousticsanctuary.com/contract/152471907280000241/).)

I wonder if you could help me figure out how to debug it. As I said, unfortunately, the plugin creator is being no help at all. Thanks!

**Comment by kevindees** [comment]
@jamminjames 

Is this the plugin? https://codecanyon.net/item/wp-online-contract/7698011

I'm not sure how much help I can be since I'm not sure what their code looks like :/

Do you have any code or more details I can look at? I hope I can help but I'm probably not going to be able to debug this particular issue. But hey, maybe there is a chance :)

**Comment by jamminjames** [comment]
Kevin, thank you very much for your offer of help. Yes, that's the plugin. However, I finally got some help from them, and the problem is solved. As I suspected, it was something very simple, but error messages were not helping, and the documentation did not warn of the problem. (I encouraged them to add something.) The problem? I had colons (:) in the label fields of the shortcode form (not in the shortcodes themselves), which was causing the error, and for that reason, the shortcodes were not displaying.
