### ISSUE TITLE
admin css

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#26]
Hi,
i just discovered typerocket and i love it, i am planning to build premium themes, and having typerocket in a core plugin, it's great because i was searching for a solution to build my custom fields without depending on an external plugin like acf etc...
i was testing everything, but my backoffice custom fields appear with no css (and effectively looking at the files the sass and css files are empty)
also for ex the insert image doesn't work...
the icons doesn't work neither for me, even the dev item appear with missing icon
and the debug messages doesn't appear
i have followed the install instructions...did i miss something

Thanks in advance !

**Comment by alexadark** [comment]
i am now looking at the video from WC raleigh
i have not done the routing part because my goal is to use it to build products themes and plugins, not websites for clients (well i will use it too, but my primary goal actually is premium themes and plugins), so i need to have typerocket included in a plugin or in the theme (but better in a core plugin that i will use as base to dev other plugins that will work with my themes) so i cannot do the rooting and the special install
is it the reason of my issue ?, and is it possible, i really hope so :-)

**Comment by alexadark** [comment]
Well i have found from where the problem come from, i am using typerocket or from inside a plugin, or from inside a child theme ( the themes i am building are from the genesis framework) and the link to js and css files is automatically set from the parent theme.
How can i change that ?

**Comment by kevindees** [comment]
Hey Alexandra,

I'm glad you are finding TypeRocket helpful. Yes, you can install TypeRocket within a plugin or a child theme. There are a number of people I know who are doing exactly what you are talking about. The system is really flexible in how you can install it. I can work up some examples in a blog post later to show you how to use it like you are talking about.

However, The key is in using TypeRock in a theme/plugin combo setup is to use the `typerocket_loaded` action and configure the `config/paths.php` locations to the places you want.

- https://typerocket.com/docs/v3/wordpress-hooks/#section-core-loaded
- https://typerocket.com/docs/v3/configuration/#section-typerocket-assets

I'll let you know when I ca work up a tutorial on the TypeRocket site to do what you are talking about. Otherwise, the links above should be what you need to do what you are trying to do.

Thanks,
Kevin

**Comment by alexadark** [comment]
Thanks to answer so quickly!
i managed to make it work in a plugin adding this to the paths
`'urls' => [
        'assets' => plugins_url( '../../',__FILE__ ) . '/typerocket/wordpress/assets',
        'components' => plugins_url( '../../',__FILE__ ) . '/typerocket/wordpress/assets/components',
    ],
`
strangely i also try to have it to the child theme like that
`
'urls' => [
        'assets' => get_stylesheet_directory() . '/typerocket/wordpress/assets',
        'components' => get_stylesheet_directory() . '/typerocket/wordpress/assets/components',
    ],
`
then the url to the files is good, but it doesn't work
it is not very important as i want to use it from the plugin, but i don't understand it doesn't work this way...

Why would i need the the typerocket_loaded hook to do that ?

**Comment by kevindees** [comment]
Hey @alexadark 

The `typerocket_loaded` hook is used to access TypeRocket functions within a plugin when TypeRocket is installed in a theme and not the plugin itself.

Theme PHP:

```php
<?php // functions.php

require ('typerocket/init.php');
```

Plugin php:

```php
add_action( 'typerocket_loaded', function() {
    tr_post_type('Book');
});
```

Thanks,
Kevin

**Comment by kevindees** [comment]
Just added: https://typerocket.com/docs/v3/installation/#section-plugin-installation

```php
<?php // paths.php
return [
    /*
    |--------------------------------------------------------------------------
    | Assets URL
    |--------------------------------------------------------------------------
    |
    | The URL where TypeRocket assets can be found.
    |
    */
    'urls' => [
        'assets' => plugin_dir_url(__DIR__ . '..') . '/wordpress/assets',
        'components' => plugin_dir_url(__DIR__ . '..') . '/wordpress/assets/components',
    ],

    // ....

];
```
