### ISSUE TITLE
having metaboxes on template pages

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#28]
Hi,
could you tell me how to add a metabox only to certain pages
for ex the front page, or certain template pages
basically how to set all the options to display them like on acf

**Comment by kevindees** [comment]
Hey @alexadark,

TypeRocket does not have this feature but instead uses the page builder to accomplish what are normally the same design requirements using the technique you are describing.

I would recommend using the [page builder plugin](https://typerocket.com/docs/v3/builder/) and components for pages. When I have seen sites looking to make dynamic meta boxes depending on the page templates it is normally because you need very custom page layout variations. The page builder plugin was designed to solve that problem exactly.

Thanks,
Kevin

**Comment by alexadark** [comment]
i am going to look at it, but i don't know if it's exactly what i need
i assimilated the page builder to what i was doing when i was using the flexible content of acf : having several component that i can drag and drop, use it several time on page etc...
I have not digged in it for the moment, but i suppose the builder use the matrix field wich is similar to the flexible content
here it's different, for ex i need to have a slider only on the home page , but it will stay on top, and will not be used several times, so it's not assimilable to a sort of builder , but really more to a custom template, where the metaboxes are defined and will not change.
Also i don't want this fields to be available on other pages trough the builder
