### ISSUE TITLE
Error on theme options

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#3]
Hi,
I'm using WP 4.2.4 along with newest TypeRocket inside my theme. From the dashboard, i was testing to save simple data on Theme Options but got this error: _Your request had an error. 404 - Not Found_

Then i looked into browser console and got this error: _PUT http://acn.divren.co/typerocket_rest_api/v1/options 404 (Not Found)_

FYI, the theme's debug config is set to be true. And there is _Notice: Undefined index: theme-options in /var/www/vhosts/divren.co/acn.divren.co/wp-content/themes/acn/frameworks/typerocket/plugins/theme-options/init.php on line 30_

Is this error from my theme side? or TypeRockets?

Thanks

**Comment by kevindees** [comment]
Hi,

This means that you still need to flush the WordPress permalinks. When you install TypeRocket it registers the api with rewrite rules for `/typerocket_rest_api/v1`.

You can flush the permalinks by going to in the admin:
1. Settings 
2. Permalinks
3. Scroll to the bottom of the page
4. Click "Save Changes"

![flush permalinks](https://cloud.githubusercontent.com/assets/348368/9196701/e08a898e-3ffb-11e5-97dd-a76ae203a069.png)

_Note: I just updated the [installation docs](https://typerocket.com/docs/installation/)._

I hope this helps. And thanks for giving TypeRocket a try!

Thanks again,
Kevin

**Comment by kevindees** [comment]
#### Folder Config

Set the TypeRocket folder configuration. I think you have already done this; but for completeness.

``` php
define('TR_FOLDER', 'frameworks/typerocket');
```

#### Bug Fix

For the _Undefined index: theme-options_: there was a bug in the `init.php` file if you were using a strict PHP error mode. This is now fixed in the master branch.

[2.0.3](https://github.com/TypeRocket/typerocket/releases/tag/v2.0.3)

#### Patch Commit

https://github.com/TypeRocket/typerocket/commit/01c6b5c19f056e785d8e90ea5e3a9aa1fc0c9cb3

Thanks,
Kevin

**Comment by kevindees** [comment]
Bug patched
