### ISSUE TITLE
Escaping fields

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#32]
Should i use the usual escaping functions esc_url etc... or the sanitize data function of typerocket and in this case how ?

When should i use the fillable fields, i didn't get very well this part...

**Comment by kevindees** [comment]
## Escape Data in Templates

Yes. You need to esc any user inout before using it in a template file. So `esc_url` should be used when needed.

### Fillable fields

You do not normally need this feature. But, it is nice to have on larger sites.

By default, TypeRocket saved any input fields that starts with the prefix `tr` to the `wp_postmeta` DB table. For example, `$form->text('Email')` creates input field HTML of `<input name="tr[email]" />`... See the `tr` prefix in the `name`.

Because TypeRocket is so flexible and saves everything you might run into issues where other plugins use the `tr` input name prefix. When this happens data you do not want saved through TypeRocket might be.

This is what the `fillable` the fillable property on the post type model class is for. It tells WordPress to limit the custom fields that are saved through TypeRocket. You do not need to set it unless you need a highly secure site. When a sites has 1-3 users it is not likely you need this feature.
