### ISSUE TITLE
How to remove the toggle editor from the the builder plugin

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#37]
I am using the builder, but i have deleted the standard editor, so i don't want the toggle anymore.
Also i would like to know how i can have the builder to other cpt
of course i can build a new builder, but as this one is here i have used it

**Comment by kevindees** [comment]
Hey,

You can add your own builder field to any post type by using the builder field instead of the plugin :)

1. https://typerocket.com/docs/v3/field-types/#section-matrix-and-builder
2. https://typerocket.com/docs/v3/field-types/#section-matrix-and-builder-making-a-component

For example, `$form->builder('My Builder');` uses:

1. `resources/visuals/my_builder/`
2. `resources/components/my_builder/`
3. `wordpress/assets/components/my_builder/`

If you do not want the toggle, add a builder field instead of the plugin. Then [disable the editor](https://typerocket.com/docs/v3/removing-the-editor-from-post-types/) for the `page` post type.

**Comment by alexadark** [comment]
Yes, that's i have done, but after building pages with the plugin, so if i change it now i will have to rebuild the pages.
but now i know ;-)

**Comment by kevindees** [comment]
You can also, use the old builder by turning off the plugin and using the builder field name:

```
$form->builder('Builder');
```
