### ISSUE TITLE
Internationalisation - will gettext wraps work?

### ISSUE THREAD

**Issue by jevgen** [TypeRocket/typerocket#43]
In standard WP way of registering strings for post types, we wrap them in gettext calls like `_('Some Name')` and it powers localisation of  theme or plugin, making PO and MO production possible.

Will this work in TypeRocket?

**Comment by kevindees** [comment]
Great question. 

Yes. But, unfortunately the best way to go about this is to override the `labels` arg with the `setArgument` method. I have not listed all the labels args here.

```php
tr_post_type('Book')->setArgument('labels', [
        'add_new'            => __('Add New'),
        'add_new_item'       => __('Add New Book'),
        'edit_item'          => __('Add New Book'),
        ....
]);
```

You need to do it this way because `tr_post_type( __('Book') );` would modify types on the fly due to translation needs. So, it is best to translate only the text that gets printed to the screen and not the post type itself. Very similar to how you would register post types in WP core.

**Comment by jevgen** [comment]
OK, so the same way with custom field labels. What about placeholders in the form and buttons?

**Comment by kevindees** [comment]
Yes,

For custom fields you will want to use the setLabel method.

```php
$form->text('Field Name', ['placeholder' => __('Enter your name...'] )->setLabel(__('Field Name'));
```

Each field with a label has the `setLabel` method. For buttons I do not think it matters since the submit button value is irrelevant.

https://typerocket.com/docs/v3/fields/#section-label

**Comment by kevindees** [comment]
Also, for repeater, matrix, and builder fields you can control labels in version v3.0.28 of core. Just run `composer update`.

https://github.com/TypeRocket/core/releases/tag/v3.0.28
