### ISSUE TITLE
Editor options

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#53]
Hi,
i really like the editor from typerocket (more than the wp one), but there is no media button
it seems to be there are there is image in the default settings, but it's not there
also i don't understand how to implement the options
```
TypeRocket.redactorSettings = {
    buttons: ['formatting','bold','italic']
}

```
i want to use shortcake ui inside the editor : https://www.billerickson.net/shortcode-ui-with-shortcake/ and it works with the media button.
it works if i add the wpEditor  , and why is it bad to use the wpEditor in the builder ?

**Comment by kevindees** [comment]
Hey @alexadark 

The WP editor is not designed to be added to or moved around the screen dynamically so we do not recommend using that fields unless you know what you are doing.

As for the redactor editor field we disabled the image button by default because it was a little buggy and needed an WP media integration. To use it you would need to build your own media integration. Also, if you might want to look into the new version of Redactor and buying a lic for it and then using that for your editor instead. The latest version does not have an open source lic so we can not update to it in TypeRocket.

https://imperavi.com/redactor/

Thanks,
Kevin

**Comment by amdeu** [comment]
Hello,

I'm still not sure how to change the redactor Settings. 

```
TypeRocket.redactorSettings = {
    formattingAdd: [ {tag: 'p', title: 'Small', class: 'small' } ]
}
```
How / in which file would I add this code ? I would like to add custom formatting. Thanks!

**Comment by kevindees** [comment]
Hey @amadeus-leopold 

You will need to add your code to the admin of WordPress using the built-in WordPress hooks. Also, you will need to follow the redactor docs here: https://imperavi.com/assets/pdf/redactor-documentation-10.pdf and https://typerocket.com/docs/v4/field-types/#section-editor

Note, I have not tested your code to see if it works.

```php
// Active Theme Directory
define('THEME_DIR', get_template_directory_uri() );

// Admin Assets
add_action('admin_enqueue_scripts', function() {
    wp_enqueue_script( 'admin-script', THEME_DIR . '/js/admin.js', [], '1.0', true );
});
```

```js
// js/admin.js
TypeRocket.redactorSettings = {
    formattingAdd: [ {tag: 'p', title: 'Small', class: 'small' } ]
}
```

**Comment by amdeu** [comment]
Hi @kevindees,

it worked perfectly, thank you!
