### ISSUE TITLE
Front-end form processing in TypeRocket

### ISSUE THREAD

**Issue by chibexme** [TypeRocket/typerocket#54]
Hi,
I want to submit a form I created through shortcode and embedded in a page to TypeRocket controller through custom route but am getting this error message: 

> Sorry, you don't have enough rights.

I did not use TypeRocket `tr_form()` function  to create the form but complied to TypeRocket fields naming convention like: `tr[first_name], tr[last_name], tr[phone_no]` etc.

Please why am I getting the error message above? 
Is there any configuration I need to do with Kernel or Middleware? If yes, how do I go about that?

Note: the user don't have to login before submitting the form because it is a custom registration form with extra fields more than default WP registration form. 

Thanks in advance.

**Comment by kevindees** [comment]
There are a number of way to handle what you are asking about. But yes, configuring your middleware and kernel would be the best way to do what you are talking about.

You are being blocked because TypeRocket out of the box tries to be as secure as possible and a user that is not logged in can be a risk so the request to save custom fields gets blocked.

Regardless, you can do what you are asking.

The main items to look into are the `resourceGlobal` and `user` middleware groups in the Kernel. You will want to replace the `IsUserOrCanEditUsers` and `AuthRead` with your own middleware versions.

For example, in the `IsUserOrCanEditUsers` middleware class you need to similar class that checks for the registration page. Then in your `User` model class make sure that you guard the fields you want to protect and make fillable the ones you do not.

```php
<?php
namespace TypeRocket\Http\Middleware;
/**
 * Class IsUserOrCanEditUsers
 *
 * Validate that is user or can edit users and if the user is not
 * invalidate the response.
 *
 * @package TypeRocket\Http\Middleware
 */
class IsUserOrCanEditUsers extends Middleware
{
    public function handle() {
        if( ! $this->request->isHook() ) {
            $currentUser = wp_get_current_user();
            $user  = get_user_by( 'id', $this->request->getRouterArg('id') );
            if ($user->ID != $currentUser->ID && ! current_user_can( 'edit_users' )) {
                $this->response->setError( 'auth', false );
                $this->response->flashNow( "Sorry, you don't have enough rights.", 'error' );
                $this->response->exitAny(401);
            }
        }
        $this->next->handle();
    }
}
```

- https://typerocket.com/docs/v3/middleware/
- https://typerocket.com/docs/v3/kernel/

I do not have a lot of documentation round this kind of functionality but you can do it.

**Comment by chibexme** [comment]
Ok. Thanks @kevindees, have gotten it working.
