### ISSUE TITLE
Not able to Add metabox in Category and Post_Tags

### ISSUE THREAD

**Issue by shahbaz-dev1** [TypeRocket/typerocket#65]
I have spent a lot of time digging up how to add form to built-in taxonomies ( category, post_tag ) but didn't find a way to add. I didn't find any reference in the documentation as well. Please guide me that how to add the metabox in built-in taxonomies.

**Comment by shahbaz-dev1** [comment]
I achieve it in a way 

```php
$cat = new \TypeRocket\Register\Taxonomy('category');
$cat->setMainForm( array( $this, 'postLayout' ) );
\TypeRocket\Register\Registry::taxonomyFormContent( $cat );
```
but for that I had to modify the registry Class to make this method public.

**Comment by kevindees** [comment]
hey @wowthemes 

I'll look into this. I have not implemented a registry for adding custom hooks for saving custom fields on existing taxonomies. I'll get this setup in core and post some docs on how to do so. Taxonomies give a little trouble because they do not use meta boxes like post types and make it easy to add custom fields.

Thanks,
Kevin

**Comment by shahbaz-dev1** [comment]
@kevindees As I said that I have achieved it easily but method `taxonomyFormContent` is private, so I have modified the core. You can either give access to this method and provide an alternate. Other than that things are working fine.

**Comment by kevindees** [comment]
@wowthemes 

I just published an update making the private method of the `Registry` class public. Let me know if this does what you were hoping.

https://github.com/TypeRocket/core/releases/tag/v3.0.45

Thanks,
Kevin
