### ISSUE TITLE
What about Gutenberg ?

### ISSUE THREAD

**Issue by fadupla** [TypeRocket/typerocket#79]
First, thanks for your work, we really appreciate using your framework 😃 

With the Gutenberg editor coming in WordPress 5.0 in 2018 and becoming the default WordPress page content editor, what is planned for TypeRocket ? 

Regards,

**Comment by kevindees** [comment]
@fadupla 

Thanks. This is a great question I know a lot of people are asking. Up to this point everyone is building WordPress sites using custom fields and I do not see that changing for a long time. Gutenberg may be the new WordPress editor but it does not mean that it will take over every post type.

I see Gutenberg being used over custom fields for posts and pages over time. However, many custom post types will not need a feature like Gutenberg. For those situations plugins like ACF and frameworks like TypeRocket will continue to excel.

TypeRocket has its own page builder field (this field can be used anywhere for any reason) but that is not the exclusive feature of TypeRocket. I can see people using Gutenberg over the TypeRocket page builder though (and that is a good thing).

As TypeRocket relates to Gutenberg I would hope that the Gutenberg API is easy enough on its own that TypeRocket would not need to fill in features for Gutenberg. However, at this point it is a little early to tell what will happen once Gutenberg is released.

Gutenberg will be a big deal of a lot of plugins and frameworks. Still, TypeRocket is a framework that goes well beyond the scope of influence that Gutenberg will have. This is because TypeRocket is much more than custom fields for post types. It is also custom fields for user profiles, taxonomies, comments and more. TypeRocket is also a framework for application development with content type creation, MVC, ORM, and routing.

There is still a long way for Gutenberg to go before anyone can really say how it will impact the WordPress community and ecosystem at large. However, it will impact everyone is one way or another.

Thanks,
Kevin
